### ISSUE TITLE
Bug: Poster Image Not Loading @ certain Resolutions

### ISSUE THREAD

**Issue by kjroelke** [justinribeiro/lite-youtube#102]
Similar to #97 and #79 and maybe food for thought for #45, I've found an odd bug/edge case.

- Minimal Demo: https://codepen.io/joontae93/pen/ZEwNbPv
- Live (publicly listed) video: https://www.youtube.com/watch?v=BeKmeuwrwaU

If I set the param `posterquality` to anything _not_ `maxresdefault`, the poster image loads fine, however the `maxresdefault` doesn't work.

Further down the page, with a seperate video, it works just fine. Not really sure what's going on, but figured I'd leave a note in case others experienced a similar edge case.

Full repo: https://github.com/kingdom-one/grow-together-conference
Live at https://growtogether.church

**Comment by Einere** [comment]
always getting "hqdefault.webp" image whatever `posterquality` value

**Comment by mdmontesinos** [comment]
Also facing the same issue. It always loads hqdefault.webp.

**Comment by justinribeiro** [comment]
> If I set the param posterquality to anything not maxresdefault, the poster image loads fine, however the maxresdefault doesn't work.

This is a known issue in the YouTube API that effects various components and libraries; `maxresdefault` is typically the last item generated and can result in gaps like your demo, which is why I don't ship it as the default in v1.5.0.

I have no control over this, and I won't add the weight to the component to do all the required checks (which would hurt the performance).

> always getting "hqdefault.webp" image whatever posterquality value

Can't reproduce that in v1.5.0.
![image](https://github.com/user-attachments/assets/ee892c9a-4e54-46aa-aa5a-b79cd6a3dfa8)

> Also facing the same issue. It always loads hqdefault.webp.

Because that is the default in v1.5.0. 
https://github.com/justinribeiro/lite-youtube/blob/785c960a72301b1316b6f3f476e2b84e67325f82/lite-youtube.ts#L90-L92

**Comment by Einere** [comment]
@justinribeiro 
oh, i checked it. it works fine now. thank you. 🙏
