### ISSUE TITLE
Video title is not displayed, poster quality remains low

### ISSUE THREAD

**Issue by daniel-abramov** [justinribeiro/lite-youtube#122]
After setting `videotitle` and `posterquality="maxresdefault"`, no title is displayed (as if no option is set) and the thumbnail is shown in a bad quality.

I reproduced the issue inside an empty Svelte project:

```
$ npm create vite@latest my-svelte-app -- --template svelte-ts
$ cd my-svelte-app
$ npm install
$ npm i @justinribeiro/lite-youtube
$ npm run dev
```

Then added `import "@justinribeiro/lite-youtube";` in the `App.svelte`, and then:

```
  <lite-youtube
    videoid="ANNKjs-XNwY"
    videotitle="Custom Title"
    posterquality="maxresdefault"
  ></lite-youtube>
```

**Result:**
- No title visible.
- Poster quality remains low for some reason (interestingly, when using the CDN version, it sometimes has a good quality).
- FWIW the "no shadow" option does not change anything in my case because there is no shadow to begin with :)

Another possibly unrelated issue is that the video always starts at the lowest possible quality. But I guess this is probably beyond the scope of this library.

PS: I've also noticed that adding the `import` in a `.svelte` file inside an Astro project fails on `export class LiteYTEmbed extends HTMLElement {` complaining that the `HTMLElement` is not defined. This does not happen in a Vite+Svelte project though.

**Comment by justinribeiro** [comment]
Using the snippet you've provided, the component is working as expected.

> No title visible.

The custom title is only used for the button and the alt text, allowing for accessibility. It is not shown visually.

> Poster quality remains low for some reason (interestingly, when using the CDN version, it sometimes has a good quality).

The component doesn't control this; it'll only load what YouTube sends for that specific version that it has. This differs alot in practice (which is why I won't use `maxresdefault` as the start point for the component as it often results in oddities in quality.

![image](https://github.com/user-attachments/assets/4fff9ad3-805e-4ef0-958e-79cf03515242)

> FWIW the "no shadow" option does not change anything in my case because there is no shadow to begin with :)

The shadow refers the backdrop that the custom CSS controls as shown in this screenshot.
![image](https://github.com/user-attachments/assets/215c7395-2c4c-4788-a1a9-1cc0092abb50)

> Another possibly unrelated issue is that the video always starts at the lowest possible quality. But I guess this is probably beyond the scope of this library.

Correct; not something that is specifically controllable.

> I've also noticed that adding the import in a .svelte file inside an Astro project fails on export class LiteYTEmbed extends HTMLElement { complaining that the HTMLElement is not defined.

Couldn't tell you offhand but if my general rule of thumb for "HTMLElement is not defined" across other libs/frameworks is something isn't quite imported in the correct context (but not something I handle at the component level).

**Comment by daniel-abramov** [comment]
Thanks for the clarifications!
