### ISSUE TITLE
Probable bug wrt capitalization

### ISSUE THREAD

**Issue by elibarzilay** [justinribeiro/lite-youtube#91]
I'm guessing that there's *some* bug here:

    case 'videoid':
    case 'playlistid':
    case 'videoTitle':
    case 'videoPlay': {

Maybe the last two should be lowercased?  And if so, then probably also the attribute name in the getter/setter should be lowercased as well?

Related, and I'm not sure about it since I don't have experience with it, but maybe they should both be included in `observedAttributes`?

**Comment by elibarzilay** [comment]
It does look like this didn't work before I changed the code...

**Comment by justinribeiro** [comment]
> but maybe they should both be included in observedAttributes
I'd have to dig back, but I think at one point they were and during the major jump they got sliced out (because folks weren't using it).

From is-it-a-bug standpoint, I suppose if you're doing reused context and flipping the title or switching a locale.

I split this patch out and added you as co-author.

**Comment by elibarzilay** [comment]
Thanks!  I'll open a separate pr for the other thing...
